apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: dl-template
spec:
  displayName: dl-template
  author:
    name: Halo
    website: "https://github.com/halo-dev"
  description: Halo 2.0 Theme base on Thymeleaf
  logo: "https://www.halo.run/logo"
  homepage: "https://github.com/halo-dev/theme-starter#readme"
  repo: "https://github.com/halo-dev/theme-starter"
  issues: "https://github.com/halo-dev/theme-starter/issues"
  settingName: "theme-starter-setting"
  configMapName: "theme-starter-configMap"
  version: "1.0.0"
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/halo-dev/plugin-starter/blob/main/LICENSE"
  customTemplates:
    page:
      - name: 关于我们
        description: 关于我们页面
        screenshot:
        file: aboutus.html
      - name: 工厂介绍
        description: 工厂介绍页面
        screenshot:
        file: factory.html